spring.application.name=atm
spring.datasource.url=jdbc:sqlite:atm.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.web.locale=en_US
spring.web.locale-resolver=fixed
spring.jackson.time-zone=UTC
